### ISSUE TITLE
zeta.cpp doesn't seemed to be used

### ISSUE THREAD

**Issue by zmertens** [CartwrightLab/dawg#19]
I never noticed this before but it doesn't appear that the `zeta.cpp` file is used anywhere in the project. It isn't even part of the `DAWG_LIB_SOURCES` in `src/lib/CMakeLists.txt`.

**Comment by reedacartwright** [comment]
Yeah, it is dead code.

**Comment by zmertens** [comment]
Does the same go for [resid.h](https://github.com/reedacartwright/dawg/blob/develop/src/include/dawg/resid.h) and [bark.h](https://github.com/reedacartwright/dawg/blob/develop/src/include/dawg/bark.h) ?

**Comment by reedacartwright** [comment]
I think resid.h is a place holder for now.

## 

Reed A. Cartwright, PhD
Barrett Honors Faculty
Assistant Professor of Genomics, Evolution, and Bioinformatics
School of Life Sciences
Human and Comparative Genomics Laboratory
The Biodesign Institute

# Arizona State University

Availability: http://links.asu.edu/CartwrightCalendar
Address: The Biodesign Institute, PO Box 875301, Tempe, AZ 85287-5301 USA
Packages: The Biodesign Institute, 1001 S. McAllister Ave, Tempe, AZ
85287-5301 USA
Office: Biodesign A-224A, 1-480-965-9949
Website: http://cartwrig.ht/
