### ISSUE TITLE
Diploid simulation

### ISSUE THREAD

**Issue by kdm9** [CartwrightLab/dawg#2]
Hi Reed,

Is it possible to simulate diploid genomes (including heterozygosity) using DAWG 2? I see no mention of this being possible, but the documentation isn't complete so I thought I'd ask here.

Cheers,
Kevin

**Comment by reedacartwright** [comment]
Hi Kevin,

Dawg 2 simulates based on a set of input trees and recombination events.  It is possible to simulate a tree and recombination events from a population genetic model and feed it into Dawg.  I've seen examples of mixing MS with seqgen, which can be modified to work with Dawg.

**Comment by kdm9** [comment]
Hi Reed,

Thanks! Now you mention it, I think I remember something about doing this using MS. If it is easy for you, a link to the example you speak of would be great.

When I've worked out how, I'll write up an example of this using DAWG, which you're welcome to include in your documentation.

Cheers,
Kevin
