### ISSUE TITLE
Location of config.h may be confusing

### ISSUE THREAD

**Issue by zmertens** [CartwrightLab/dawg#22]
I ran into this issue trying to link against the dawg headers. The path to `config.h` as specified in the `dawg/details/mutt.h` file is:

``` c
#ifndef DAWG_NO_CONFIG_H
#   include <dawg/details/config.h>
#endif
```

But the `config.h` file is located in the top-level `src/` directory. I think CMAKE resolves this using `config.h.cmake`; I ran into this issue trying to link against the dawg headers and library files (without using CMAKE), so I am wondering if `config.h` should be included within the `dawg/details` directory?

**Comment by reedacartwright** [comment]
Yes, it should be installed alongside the other headers, I believe.

## 

Reed A. Cartwright, PhD
Barrett Honors Faculty
Assistant Professor of Genomics, Evolution, and Bioinformatics
School of Life Sciences
Human and Comparative Genomics Laboratory
The Biodesign Institute

# Arizona State University

Availability: http://links.asu.edu/CartwrightCalendar
Address: The Biodesign Institute, PO Box 875301, Tempe, AZ 85287-5301 USA
Packages: The Biodesign Institute, 1001 S. McAllister Ave, Tempe, AZ
85287-5301 USA
Office: Biodesign A-224A, 1-480-965-9949
Website: http://cartwrig.ht/

**Comment by zmertens** [comment]
It works for a standard path it looks like (such as the default `/usr/local`). The issue I ran into appears that only `config.h` will be installed if the install prefix is non-standard. So, I think it's not a real issue since most users would presumably use the standard path.

**Comment by reedacartwright** [comment]
If it doesn't work for installing to a non-standard prefix, then we need to
fix that.

## 

Reed A. Cartwright, PhD
Barrett Honors Faculty
Assistant Professor of Genomics, Evolution, and Bioinformatics
School of Life Sciences
Human and Comparative Genomics Laboratory
The Biodesign Institute

# Arizona State University

Availability: http://links.asu.edu/CartwrightCalendar
Address: The Biodesign Institute, PO Box 875301, Tempe, AZ 85287-5301 USA
Packages: The Biodesign Institute, 1001 S. McAllister Ave, Tempe, AZ
85287-5301 USA
Office: Biodesign A-224A, 1-480-965-9949
Website: http://cartwrig.ht/

**Comment by zmertens** [comment]
Just tested non-standard path and it installs the headers correctly as well.
