### ISSUE TITLE
issues compiling on GNU/Linux

### ISSUE THREAD

**Issue by stuckyb** [CartwrightLab/dawg#25]
First, thanks for your work on DAWG and for making the source code freely available.  I recently tried compiling the 1.2 source on a recent version of Xubuntu GNU/Linux (gcc 5.2.1), and I got "not declared in this scope" errors for two functions: memcpy() and strchr().  To fix this, I added the line

```
#include <cstring>
```

to `matrix.cpp` and `output.cpp`; this resolved the error messages.  I realize that this might already be addressed in the development version of the code, but many users will want to stick with the latest release, so it might be useful to add some documentation somewhere indicating how to fix this problem.

**Comment by zmertens** [comment]
Thanks for reporting this issue. Out of curiousity, did you build from [master](https://github.com/reedacartwright/dawg/tree/master) or the [release](https://github.com/reedacartwright/dawg/releases/tag/v1.2) ?

**Comment by stuckyb** [comment]
It was the 1.2 release.

**Comment by reedacartwright** [comment]
Try compiling from the master branch, the missing header bug was fixed in 59d94fffcfe.
