### ISSUE TITLE
Allow user to specify root sequence

### ISSUE THREAD

**Issue by zmertens** [CartwrightLab/dawg#35]
- [ ] Added three new `do` functions to `dawg::root_model`
    - [ ] `do_user_seq`
    - [ ] `do_user_rates`
    - [ ] `do_user_seq_rates`

- [ ] Modify `dawg::root_model::create` to select the do functions based on whether rates or seq are empty

**Comment by zmertens** [comment]
How does Dawg currently handle the root sequence? I thought it might be mocked in 'matic.cpp' but could not find it.

**Comment by reedacartwright** [comment]
Each `matic_section` has a `root_model rut_mod` member variable.

https://github.com/reedacartwright/dawg/blob/9c44bdc8cb1ebbfca4cddf4976841d734cf09288/src/include/dawg/matic.h#L53

https://github.com/reedacartwright/dawg/blob/9c44bdc8cb1ebbfca4cddf4976841d734cf09288/src/lib/matic.cpp#L65

**Comment by zmertens** [comment]
Where are the root sequence and rates used? Are they part of the `sequence` structure?

**Comment by reedacartwright** [comment]
Each residue in a sequence has a base and a rate associated with it.  `do_stat` generates these from a model: https://github.com/reedacartwright/dawg/blob/9c44bdc8cb1ebbfca4cddf4976841d734cf09288/src/include/dawg/root.h#L41-L42

The other do_ functions will need to either generate them from a model or use the values specified by the user.

**Comment by zmertens** [comment]
> The other do_ functions will need to either generate them from a model or use the values specified by the user.

Oh, that's straightforward. I saw the `rate_cat` but I confused `base` and `root_seq`.

**Comment by reedacartwright** [comment]
Fixed in #36
