### ISSUE TITLE
In output.cpp, throw error quickly if filepath doesn't exist

### ISSUE THREAD

**Issue by zmertens** [CartwrightLab/dawg#4]
I was wondering if it would be worthwhile to throw an error quickly when trying to open an output file using Boost's Filesystem library. For instance, in `output.cpp` in the `dawg::output::open` function there could be

``` c
if(!boost::filesystem::exists(file_name)) {
    return DAWG_ERROR("file does not exist: \'" << file_name << "\'.");
}
```

**Comment by reedacartwright** [comment]
If `file_name` does not exist, it is not an error. The file will be created upon opening for receiving output. Also `file_name` may be prefixed with a filetype, e.g. `aln:output.txt` and needs to be parsed to extract the output path before opening the file.

**Comment by zmertens** [comment]
I should've specified this error handling is specifically for when the user specifies a filepath that doesn't exist. The rationality is to avoid finding the file extension and trying to create the file and then receiving an error at line 66:

``` c
if(!do_split) {
    if(!open_file(file_name))
        return DAWG_ERROR("unable to open output file \'" << file_name << "\'.");
} else {
```

One thing to add, is that there would be a check on the `file_name` being passed in to ensure that _only_ the directory is validated. For instance:

``` c
/home/user/dawg-out/file_name
```

would be valid assuming the directory `/home/user/dawg-out/` exists since `file_name` will get created if it doesn't already exist. If `/home/user/dawg-out/` does not exist then the error would get thrown before performing any other operations.
