### ISSUE TITLE
Position of Output.Rna in a dawg trick file should not matter?

### ISSUE THREAD

**Issue by zmertens** [CartwrightLab/dawg#47]
Consider this file, it should print out an RNA sequence correctly:
```python
Output.Rna = 1
[Tree]
Tree = "((Man:0.1,Monkey:0.1):0.2,Dawg:0.25);"
[Subst]
Model = "HKY"
Params = 2.0, 1.0 
Freqs = 0.3, 0.2, 0.2, 0.3
[Root]
Length = 1000
[Sim]
Reps = 10
```

However, if the RNA output specifier is moved to the bottom, it will not print out an RNA sequence.
```python
[Tree]
Tree = "((Man:0.1,Monkey:0.1):0.2,Dawg:0.25);"
[Subst]
Model = "HKY"
Params = 2.0, 1.0 
Freqs = 0.3, 0.2, 0.2, 0.3
[Root]
Length = 1000
[Sim]
Reps = 10
Output.Rna = 1
```

I think this might be something worth investigating and fixing? 
On a side note,  and relevant to the RootSequence patch, should the user be able to specify an RNA sequence as the root sequence?

**Comment by reedacartwright** [comment]
Works as expected.

I your second example, you have places Output.Rna in the `[Sim]` section so it gets read as `Sim.Output.Rna`
