### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by dlaehnemann** [CartwrightLab/dawg#53]
Dear @reedacartwright, @zmertens,

thanks for providing and developing this tool. We would like to use it as one step in a simulation pipeline, and for this purpose I would like to package it for [bioconda](https://bioconda.github.io), the bioinformatics software / package channel of the cross-platform package manager [conda](https://conda.io/docs/index.html). For software in GitHub repositories, this is best done via GitHub releases, and I was thus wondering if you would be willing to create a new release in the near future, as a lot of development seems to have happened since the last release of version 1.2 in 2009.

Thanks and best regards,
David

**Comment by reedacartwright** [comment]
Hi David,

A lot of testing still needs to happen with the develop branch before I'm going to spin off a new release. I might create a "beta" tag if it is absolute necessary. I recommend using a commit ID until a new release occurs.

**Comment by dlaehnemann** [comment]
Hi Reed,

thanks for the quick response!

Proper testing is very much appreciated, so maybe we'll wait for a proper release and use another simulation tool without indel support for now. Do you have any rough idea when a new release might land? Or would you be confident that basic functionality would work well in a current beta-release?

And a quick bioconda-reference for context on using commit IDs: [bioconda recommends against it, as release tarballs are considered more stable urls](https://bioconda.github.io/guidelines.html#stable-url).

cheers,
david

**Comment by reedacartwright** [comment]
Hi David,

I'm confident in the functionality in the develop branch. I use it in production code and recommend it to collaborators. Testing has less to do with ensuring accuracy at this point than to ensure that it compiles correctly. Bioconda will take care of that.

As far as when I will be comfortable tagging a release, I do not know. I need to find a good month to put a lot of effort into the repository, or find a grad student who has the right skill set to focus on it.

Commit IDs are almost as stable as releases. For instance if you wanted to use tarball of the current develop branch, you can use https://github.com/reedacartwright/dawg/archive/e471fdb1c47d443779c4d1c2a289b79ab339c020.tar.gz

**Comment by dlaehnemann** [comment]
Hi Reed,

thanks again for the detailed reply and the pointer to the tarball. I would then go and try creating a bioconda release from that one beginning of next week.

As I don't want to mess up your version numbering, do you have a preference of version number to assign to the bioconda package? Here's what [bioconda refers to](https://bioconda.github.io/guidelines.html#packages-appropriate-for-bioconda) as schemes allowed by conda:
https://github.com/conda/conda/blob/d1348cf3eca0f78093c7c46157989509572e9c25/conda/version.py#L30

From what I see there, something like a `beta` version of an upcoming release version number (`2.0.beta1`?) would make sense to me, or something of a `post` version of the last release (`1.2.post1`?)--intuitively I'd go for the first option...

cheers,
david

**Comment by reedacartwright** [comment]
2.0.beta1 makes sense.

**Comment by dlaehnemann** [comment]
Hi Reed,

thanks again for the feedback. I have now packaged dawg for bioconda with the suggested version number: https://github.com/bioconda/bioconda-recipes/pull/8725

It should be available for installation in an hour or two, once it has been packaged and uploaded to the package archive. Once we use it in our pipeline, I'll also let you know.

cheers,
david

**Comment by Morteza-M-Saber** [comment]
@dlaehnemann Thanks for putting dawg in Bioconda. I installed it using conda but I am not able to run it. Could you explain how it can be used once installed by 'Conda install dawg'?
